### PR TITLE
Added postgresql deployment and db initialization to guacamole manifests

### PR DESCRIPTION
**Pull request by maurice-arends**
readme.md in /kubernetes.guacamole needs updating

### CODE REVIEW

**Comment by thedatabaseme** [comment]
@maurice-arends Thanks for contributing. In general that's a good idea. But I have some remarks on that. Give me some days to review / comment here. I'm quite busy atm.

Kind regards
Philip

**Comment by thedatabaseme** [comment]
@maurice-arends I've added my comments. If you need assistance in creating an overlay and kustomization patches, let me know.

**Comment by maurice-arends** [comment]
I can't see any comments other than those posted here, perhaps a permission issue?

**Comment by thedatabaseme** [comment]
> I can't see any comments other than those posted here, perhaps a permission issue?

They are inline code. You can see those under files.

**Comment by maurice-arends** [comment]
As stated before, I can't see the comments. You may have to check permissions, or just post them here.

**Comment by thedatabaseme** [comment]
@maurice-arends 
grafik

**Comment by thedatabaseme** [comment]
@maurice-arends 
grafik

**Comment by thedatabaseme** [comment]
@maurice-arends 
grafik

**Pull request closed without merging**
